import Head from "next/head";

import { Flex, Box } from "@chakra-ui/react";

import { baseUrl, fetchApi } from "../utils/fetchApi";
import Property from "../components/Property";
import Testimonials from "../components/Testimonials";
import Hero from "../components/Hero";

export default function Home({ propertiesForSale, propertiesForRent }) {
  return (
    <Box>
      <Head>
        <title>avioo: your home = your dream</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        title1="Rental Homes"
        title2="For Everyone"
        desc1=" Explore from Apartments, builder floors, villas, studio appartment, shared appartment and more..."
        buttonText1="Explore Renting"
        buttonText2="How it Works"
        linkName="/search?purpose=for-rent"
        imageUrl="https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cmVhbCUyMGVzdGF0ZXxlbnwwfDB8MHx8&auto=format&fit=crop&w=500&q=60"
      />

      <Flex flexWrap="wrap">
        {propertiesForRent.map((property) => (
          <Property property={property} key={property.id} />
        ))}
      </Flex>

      <Hero
        title1="Buy Home"
        title2="Make your Dream"
        desc1="Explore from Apartments, builder floors, villas, studio appartment, shared appartment and more..."
        buttonText1="Explore Buying"
        buttonText2="How it Works"
        linkName="/search?purpose=for-sale"
        imageUrl="https://images.unsplash.com/photo-1560184897-ae75f418493e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHJlYWwlMjBlc3RhdGV8ZW58MHwwfDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60"
      />
      <Flex flexWrap="wrap">
        {propertiesForSale.map((property) => (
          <Property property={property} key={property.id} />
        ))}
      </Flex>

      <Testimonials />
    </Box>
  );
}

export async function getStaticProps() {
  const propertyForSale = await fetchApi(
    `${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-sale&hitsPerPage=6`
  );
  const propertyForRent = await fetchApi(
    `${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-rent&hitsPerPage=6`
  );

  return {
    props: {
      propertiesForSale: propertyForSale?.hits,
      propertiesForRent: propertyForRent?.hits,
    },
  };
}
